In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1=["arun",2,4,5,9968.6,True]

In [5]:
a1=np.array(l1)

In [6]:
a1

array(['arun', '2', '4', '5', '9968.6', 'True'], dtype='<U32')

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2=np.array([[1,2,3],[4,5,6]])

In [9]:
a3=np.array([[[1,3,4],[4,5,6],[7,8,9]]])

In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a3

array([[[1, 3, 4],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
#dim used for shows the dimension of array
a1.ndim

1

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

In [17]:
#size command shows the no.of element in the array
a1.size

6

In [18]:
a2.size

6

In [19]:
a3.size

9

In [21]:
a1.shape

(6,)

In [22]:
a2.shape

(2, 3)

In [23]:
# inthis example 3,3 shows the no. of rows  and no. of columns 
a3.shape

(1, 3, 3)

In [24]:
np.random.randint(3,50,(3,4))

array([[ 4, 18, 34,  4],
       [10,  6,  7, 16],
       [47,  5, 10, 12]])

In [25]:
np.random.rand(5,4)

array([[0.01871405, 0.22981603, 0.51636882, 0.55752572],
       [0.27855486, 0.62722916, 0.85740784, 0.41952366],
       [0.44040629, 0.684785  , 0.48443268, 0.15145852],
       [0.84011888, 0.60001837, 0.27965501, 0.57299276],
       [0.0822437 , 0.21613433, 0.16292603, 0.51634995]])

In [26]:
a4=np.random.randn(4,4)

In [27]:
a4

array([[-2.00332113, -0.09959506, -0.5426018 ,  0.06299922],
       [ 0.4037467 ,  1.21635067, -0.13025586, -0.86157063],
       [ 1.0164471 , -1.08266644,  0.66602827,  0.60691225],
       [-0.25049943,  0.04143612,  0.86780709, -0.71858936]])

In [29]:
#for reshape must have no.of element should be same as pervious 
a4.reshape(2,8)

array([[-2.00332113, -0.09959506, -0.5426018 ,  0.06299922,  0.4037467 ,
         1.21635067, -0.13025586, -0.86157063],
       [ 1.0164471 , -1.08266644,  0.66602827,  0.60691225, -0.25049943,
         0.04143612,  0.86780709, -0.71858936]])

In [30]:
a4.reshape(8,2)

array([[-2.00332113, -0.09959506],
       [-0.5426018 ,  0.06299922],
       [ 0.4037467 ,  1.21635067],
       [-0.13025586, -0.86157063],
       [ 1.0164471 , -1.08266644],
       [ 0.66602827,  0.60691225],
       [-0.25049943,  0.04143612],
       [ 0.86780709, -0.71858936]])

In [31]:
a4.reshape(16,1)

array([[-2.00332113],
       [-0.09959506],
       [-0.5426018 ],
       [ 0.06299922],
       [ 0.4037467 ],
       [ 1.21635067],
       [-0.13025586],
       [-0.86157063],
       [ 1.0164471 ],
       [-1.08266644],
       [ 0.66602827],
       [ 0.60691225],
       [-0.25049943],
       [ 0.04143612],
       [ 0.86780709],
       [-0.71858936]])

In [33]:
a4.reshape(2,-1345643649999)

array([[-2.00332113, -0.09959506, -0.5426018 ,  0.06299922,  0.4037467 ,
         1.21635067, -0.13025586, -0.86157063],
       [ 1.0164471 , -1.08266644,  0.66602827,  0.60691225, -0.25049943,
         0.04143612,  0.86780709, -0.71858936]])

In [38]:
a4.reshape(2,-1)

array([[-2.00332113, -0.09959506, -0.5426018 ,  0.06299922,  0.4037467 ,
         1.21635067, -0.13025586, -0.86157063],
       [ 1.0164471 , -1.08266644,  0.66602827,  0.60691225, -0.25049943,
         0.04143612,  0.86780709, -0.71858936]])

In [39]:
a4.reshape(8,-1)

array([[-2.00332113, -0.09959506],
       [-0.5426018 ,  0.06299922],
       [ 0.4037467 ,  1.21635067],
       [-0.13025586, -0.86157063],
       [ 1.0164471 , -1.08266644],
       [ 0.66602827,  0.60691225],
       [-0.25049943,  0.04143612],
       [ 0.86780709, -0.71858936]])

In [40]:
a4.reshape(16,-1)

array([[-2.00332113],
       [-0.09959506],
       [-0.5426018 ],
       [ 0.06299922],
       [ 0.4037467 ],
       [ 1.21635067],
       [-0.13025586],
       [-0.86157063],
       [ 1.0164471 ],
       [-1.08266644],
       [ 0.66602827],
       [ 0.60691225],
       [-0.25049943],
       [ 0.04143612],
       [ 0.86780709],
       [-0.71858936]])

In [41]:
a1

array(['arun', '2', '4', '5', '9968.6', 'True'], dtype='<U32')

In [42]:
a1[0]

'arun'

In [43]:
a1[2:6]

array(['4', '5', '9968.6', 'True'], dtype='<U32')

In [44]:
a1[2:6:2]

array(['4', '9968.6'], dtype='<U32')

In [45]:
a1[::-1]

array(['True', '9968.6', '5', '4', '2', 'arun'], dtype='<U32')

In [46]:
a3

array([[[1, 3, 4],
        [4, 5, 6],
        [7, 8, 9]]])

In [47]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
  a2[:,1:]

array([[2, 3],
       [5, 6]])

In [62]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [66]:
a2[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [67]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [68]:
#genrate random no. b/w 2 to 90 
a5=np.random.randint(2,90,(6,5))

In [69]:
a5

array([[12, 63, 41, 15, 65],
       [ 6, 13, 39, 43, 71],
       [51, 28, 73, 40, 71],
       [59,  7, 69, 20, 79],
       [71, 17, 68, 15, 12],
       [54, 24, 72, 59, 62]])

In [70]:
a5[a5>50]

array([63, 65, 71, 51, 73, 71, 59, 69, 79, 71, 68, 54, 72, 59, 62])

In [71]:
a5

array([[12, 63, 41, 15, 65],
       [ 6, 13, 39, 43, 71],
       [51, 28, 73, 40, 71],
       [59,  7, 69, 20, 79],
       [71, 17, 68, 15, 12],
       [54, 24, 72, 59, 62]])

In [72]:
a5[0,1]=100

In [73]:
a5

array([[ 12, 100,  41,  15,  65],
       [  6,  13,  39,  43,  71],
       [ 51,  28,  73,  40,  71],
       [ 59,   7,  69,  20,  79],
       [ 71,  17,  68,  15,  12],
       [ 54,  24,  72,  59,  62]])

In [74]:
a6=np.random.randint(0,3,(3,3))

In [75]:
a7=np.random.randint(0,3,(3,3))

In [76]:
a6

array([[1, 1, 0],
       [2, 1, 2],
       [0, 1, 1]])

In [77]:
a7

array([[0, 1, 0],
       [0, 2, 2],
       [2, 1, 2]])

In [79]:
# '*' is for element wise multiplication of matrix
a6*a7

array([[0, 1, 0],
       [0, 2, 4],
       [0, 1, 2]])

In [80]:
# '@'command used for matrix multiplication
a6@a7

array([[0, 3, 2],
       [4, 6, 6],
       [2, 3, 4]])

In [81]:
a6

array([[1, 1, 0],
       [2, 1, 2],
       [0, 1, 1]])

In [82]:
a6+100

array([[101, 101, 100],
       [102, 101, 102],
       [100, 101, 101]])

In [83]:
a6/0

C:\Users\MIET\AppData\Local\Temp\ipykernel_4004\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\MIET\AppData\Local\Temp\ipykernel_4004\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, nan],
       [inf, inf, inf],
       [nan, inf, inf]])

In [84]:
#'**' for power of each element
a6**3

array([[1, 1, 0],
       [8, 1, 8],
       [0, 1, 1]], dtype=int32)

In [85]:
a8=np.zeros((4,4))

In [86]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
a9=np.ones((4,5))

In [88]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [91]:
a9+np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [92]:
np.array([1,2,3,4,5]).T

array([1, 2, 3, 4, 5])

In [93]:
#'T'command use for Transpose.
# for transpose min two dimension is needed
np.array([[1,2,3,4,5]]).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [95]:
np.array([[1,2,3,4]]).T +a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [97]:
a9+np.array([[1,2,3,4]]).T

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [98]:
a6.T

array([[1, 2, 0],
       [1, 1, 1],
       [0, 2, 1]])

In [99]:
a6

array([[1, 1, 0],
       [2, 1, 2],
       [0, 1, 1]])

In [100]:
a5

array([[ 12, 100,  41,  15,  65],
       [  6,  13,  39,  43,  71],
       [ 51,  28,  73,  40,  71],
       [ 59,   7,  69,  20,  79],
       [ 71,  17,  68,  15,  12],
       [ 54,  24,  72,  59,  62]])

In [101]:
np.sqrt(a5)

array([[ 3.46410162, 10.        ,  6.40312424,  3.87298335,  8.06225775],
       [ 2.44948974,  3.60555128,  6.244998  ,  6.55743852,  8.42614977],
       [ 7.14142843,  5.29150262,  8.54400375,  6.32455532,  8.42614977],
       [ 7.68114575,  2.64575131,  8.30662386,  4.47213595,  8.88819442],
       [ 8.42614977,  4.12310563,  8.24621125,  3.87298335,  3.46410162],
       [ 7.34846923,  4.89897949,  8.48528137,  7.68114575,  7.87400787]])

In [102]:
np.exp(a5)

array([[1.62754791e+05, 2.68811714e+43, 6.39843494e+17, 3.26901737e+06,
        1.69488924e+28],
       [4.03428793e+02, 4.42413392e+05, 8.65934004e+16, 4.72783947e+18,
        6.83767123e+30],
       [1.40934908e+22, 1.44625706e+12, 5.05239363e+31, 2.35385267e+17,
        6.83767123e+30],
       [4.20121040e+25, 1.09663316e+03, 9.25378173e+29, 4.85165195e+08,
        2.03828107e+34],
       [6.83767123e+30, 2.41549528e+07, 3.40427605e+29, 3.26901737e+06,
        1.62754791e+05],
       [2.83075330e+23, 2.64891221e+10, 1.85867175e+31, 4.20121040e+25,
        8.43835667e+26]])

In [103]:
np.log10(a5)

array([[1.07918125, 2.        , 1.61278386, 1.17609126, 1.81291336],
       [0.77815125, 1.11394335, 1.59106461, 1.63346846, 1.85125835],
       [1.70757018, 1.44715803, 1.86332286, 1.60205999, 1.85125835],
       [1.77085201, 0.84509804, 1.83884909, 1.30103   , 1.89762709],
       [1.85125835, 1.23044892, 1.83250891, 1.17609126, 1.07918125],
       [1.73239376, 1.38021124, 1.8573325 , 1.77085201, 1.79239169]])

In [104]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [105]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [106]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [107]:
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [108]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [109]:
# 'logspace'Return numbers spaced evenly on a log scale.
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [110]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])